# Generated by Django 5.2.10 on 2026-01-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_supplier_email_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
