# Generated by Django 5.2.10 on 2026-01-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
