# Generated by Django 5.2.10 on 2026-01-24 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_product_image_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.supplier'),
        ),
    ]
